// default package
// Generated 13 mars 2015 14:48:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Classe generated by hbm2java
 */
public class Classe implements java.io.Serializable {

	private int id;
	private Set etudiants = new HashSet(0);

	public Classe() {
	}

	public Classe(int id) {
		this.id = id;
	}

	public Classe(int id, Set etudiants) {
		this.id = id;
		this.etudiants = etudiants;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public Set getEtudiants() {
		return this.etudiants;
	}

	public void setEtudiants(Set etudiants) {
		this.etudiants = etudiants;
	}

}
