// default package
// Generated 13 mars 2015 14:48:19 by Hibernate Tools 3.4.0.CR1

/**
 * EtudiantMatiereId generated by hbm2java
 */
public class EtudiantMatiereId implements java.io.Serializable {

	private int etudiantId;
	private int matiereId;

	public EtudiantMatiereId() {
	}

	public EtudiantMatiereId(int etudiantId, int matiereId) {
		this.etudiantId = etudiantId;
		this.matiereId = matiereId;
	}

	public int getEtudiantId() {
		return this.etudiantId;
	}

	public void setEtudiantId(int etudiantId) {
		this.etudiantId = etudiantId;
	}

	public int getMatiereId() {
		return this.matiereId;
	}

	public void setMatiereId(int matiereId) {
		this.matiereId = matiereId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof EtudiantMatiereId))
			return false;
		EtudiantMatiereId castOther = (EtudiantMatiereId) other;

		return (this.getEtudiantId() == castOther.getEtudiantId())
				&& (this.getMatiereId() == castOther.getMatiereId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getEtudiantId();
		result = 37 * result + this.getMatiereId();
		return result;
	}

}
