// default package
// Generated 13 mars 2015 14:48:19 by Hibernate Tools 3.4.0.CR1

/**
 * EtudiantMatiere generated by hbm2java
 */
public class EtudiantMatiere implements java.io.Serializable {

	private EtudiantMatiereId id;
	private Etudiant etudiant;
	private Matiere matiere;

	public EtudiantMatiere() {
	}

	public EtudiantMatiere(EtudiantMatiereId id, Etudiant etudiant,
			Matiere matiere) {
		this.id = id;
		this.etudiant = etudiant;
		this.matiere = matiere;
	}

	public EtudiantMatiereId getId() {
		return this.id;
	}

	public void setId(EtudiantMatiereId id) {
		this.id = id;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

}
