// default package
// Generated 13 mars 2015 14:48:19 by Hibernate Tools 3.4.0.CR1

/**
 * MatiereEtudiantId generated by hbm2java
 */
public class MatiereEtudiantId implements java.io.Serializable {

	private int matiereId;
	private int etudiantId;

	public MatiereEtudiantId() {
	}

	public MatiereEtudiantId(int matiereId, int etudiantId) {
		this.matiereId = matiereId;
		this.etudiantId = etudiantId;
	}

	public int getMatiereId() {
		return this.matiereId;
	}

	public void setMatiereId(int matiereId) {
		this.matiereId = matiereId;
	}

	public int getEtudiantId() {
		return this.etudiantId;
	}

	public void setEtudiantId(int etudiantId) {
		this.etudiantId = etudiantId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof MatiereEtudiantId))
			return false;
		MatiereEtudiantId castOther = (MatiereEtudiantId) other;

		return (this.getMatiereId() == castOther.getMatiereId())
				&& (this.getEtudiantId() == castOther.getEtudiantId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getMatiereId();
		result = 37 * result + this.getEtudiantId();
		return result;
	}

}
