// default package
// Generated 13 mars 2015 14:48:19 by Hibernate Tools 3.4.0.CR1

/**
 * MatiereEtudiant generated by hbm2java
 */
public class MatiereEtudiant implements java.io.Serializable {

	private MatiereEtudiantId id;
	private Etudiant etudiant;
	private Matiere matiere;

	public MatiereEtudiant() {
	}

	public MatiereEtudiant(MatiereEtudiantId id, Etudiant etudiant,
			Matiere matiere) {
		this.id = id;
		this.etudiant = etudiant;
		this.matiere = matiere;
	}

	public MatiereEtudiantId getId() {
		return this.id;
	}

	public void setId(MatiereEtudiantId id) {
		this.id = id;
	}

	public Etudiant getEtudiant() {
		return this.etudiant;
	}

	public void setEtudiant(Etudiant etudiant) {
		this.etudiant = etudiant;
	}

	public Matiere getMatiere() {
		return this.matiere;
	}

	public void setMatiere(Matiere matiere) {
		this.matiere = matiere;
	}

}
